"""
Static ticker-to-GICS sector mapping.
Used as fallback when stock_cache table has no sector data for a ticker.
Covers all tickers in build_asset_library.py + TRACKED_SECURITIES + ETFs.
"""

SECTOR_MAP: dict[str, str] = {
    # --- Technology ---
    "AAPL": "Technology",
    "MSFT": "Technology",
    "NVDA": "Technology",
    "AVGO": "Technology",
    "ADBE": "Technology",
    "CRM": "Technology",
    "CSCO": "Technology",
    "INTC": "Technology",
    "AMD": "Technology",
    "TXN": "Technology",
    "INTU": "Technology",
    "AMAT": "Technology",
    "ORCL": "Technology",
    "ACN": "Technology",
    "LRCX": "Technology",
    "KLAC": "Technology",
    "NOW": "Technology",
    "SNOW": "Technology",
    "DDOG": "Technology",
    "OKTA": "Technology",
    "ZS": "Technology",
    "CRWD": "Technology",
    "PANW": "Technology",
    "FTNT": "Technology",
    "NET": "Technology",
    "MDB": "Technology",
    "TEAM": "Technology",
    "TWLO": "Technology",
    "DOCU": "Technology",
    "SAP": "Technology",
    "SIEGY": "Technology",
    "TSM": "Technology",
    "ASML": "Technology",
    "FIS": "Technology",
    "FISV": "Technology",
    "GPN": "Technology",
    "PYPL": "Technology",
    "SQ": "Technology",
    "SHOP": "Technology",
    "XLK": "Technology",

    # --- Communication Services ---
    "GOOGL": "Communication Services",
    "GOOG": "Communication Services",
    "META": "Communication Services",
    "DIS": "Communication Services",
    "NFLX": "Communication Services",
    "SNAP": "Communication Services",
    "PINS": "Communication Services",
    "MTCH": "Communication Services",
    "TTD": "Communication Services",
    "ROKU": "Communication Services",
    "SPOT": "Communication Services",
    "ZM": "Communication Services",
    "EA": "Communication Services",
    "TTWO": "Communication Services",
    # ATVI delisted (acquired by MSFT Oct 2023) — removed
    "NTES": "Communication Services",
    "BIDU": "Communication Services",
    "TCEHY": "Communication Services",
    "XLC": "Communication Services",

    # --- Consumer Discretionary ---
    "AMZN": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "HD": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "LOW": "Consumer Discretionary",
    "BKNG": "Consumer Discretionary",
    "TJX": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "MAR": "Consumer Discretionary",
    "TGT": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "UBER": "Consumer Discretionary",
    "LYFT": "Consumer Discretionary",
    "ABNB": "Consumer Discretionary",
    "DASH": "Consumer Discretionary",
    "RBLX": "Consumer Discretionary",
    "HLT": "Consumer Discretionary",
    "H": "Consumer Discretionary",
    "IHG": "Consumer Discretionary",
    "CCL": "Consumer Discretionary",
    "RCL": "Consumer Discretionary",
    "NCLH": "Consumer Discretionary",
    "JD": "Consumer Discretionary",
    "PDD": "Consumer Discretionary",
    "BABA": "Consumer Discretionary",
    "NIO": "Consumer Discretionary",
    "XPEV": "Consumer Discretionary",
    "LI": "Consumer Discretionary",
    "XLY": "Consumer Discretionary",

    # --- Consumer Staples ---
    "PG": "Consumer Staples",
    "COST": "Consumer Staples",
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "WMT": "Consumer Staples",
    "PM": "Consumer Staples",
    "MO": "Consumer Staples",
    "CVS": "Consumer Staples",
    "WBA": "Consumer Staples",
    "XLP": "Consumer Staples",

    # --- Energy ---
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "PSX": "Energy",
    "PXD": "Energy",
    "OXY": "Energy",
    "SLB": "Energy",
    "HAL": "Energy",
    "BKR": "Energy",
    "DVN": "Energy",
    "FANG": "Energy",
    "MRO": "Energy",
    "APA": "Energy",
    "OVV": "Energy",
    "CTRA": "Energy",
    "PR": "Energy",
    "VLO": "Energy",
    "MPC": "Energy",
    "EOG": "Energy",
    "SU": "Energy",
    "ENB": "Energy",
    "XLE": "Energy",
    "OIH": "Energy",
    # USO is an oil commodity ETF — classified under Commodities, not Energy

    # --- Financials ---
    "JPM": "Financials",
    "V": "Financials",
    "MA": "Financials",
    "BAC": "Financials",
    "WFC": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "BLK": "Financials",
    "C": "Financials",
    "AXP": "Financials",
    "SPGI": "Financials",
    "CB": "Financials",
    "CME": "Financials",
    "ICE": "Financials",
    "PGR": "Financials",
    "AON": "Financials",
    "TRV": "Financials",
    "ALL": "Financials",
    "AIG": "Financials",
    "PRU": "Financials",
    "MET": "Financials",
    "PFG": "Financials",
    "AFL": "Financials",
    "USB": "Financials",
    "PNC": "Financials",
    "TFC": "Financials",
    "COF": "Financials",
    "DFS": "Financials",
    "SYF": "Financials",
    "BK": "Financials",
    "STT": "Financials",
    "SCHW": "Financials",
    "MSCI": "Financials",
    "MCO": "Financials",
    "COIN": "Financials",
    "BRK.B": "Financials",
    "RY": "Financials",
    "TD": "Financials",
    "BNS": "Financials",
    "BMO": "Financials",
    "CM": "Financials",
    "XLF": "Financials",
    "KBE": "Financials",
    "KRE": "Financials",

    # --- Health Care ---
    "UNH": "Health Care",
    "LLY": "Health Care",
    "MRK": "Health Care",
    "ABBV": "Health Care",
    "ABT": "Health Care",
    "TMO": "Health Care",
    "MDT": "Health Care",
    "SYK": "Health Care",
    "ISRG": "Health Care",
    "ELV": "Health Care",
    "GILD": "Health Care",
    "BMY": "Health Care",
    "AMGN": "Health Care",
    "CI": "Health Care",
    "BDX": "Health Care",
    "ZTS": "Health Care",
    "BSX": "Health Care",
    "HUM": "Health Care",
    "HCA": "Health Care",
    "REGN": "Health Care",
    "MCK": "Health Care",
    "DHR": "Health Care",
    "A": "Health Care",
    "WAT": "Health Care",
    "MTD": "Health Care",
    "PKI": "Health Care",
    "IDXX": "Health Care",
    "IQV": "Health Care",
    "CRL": "Health Care",
    "ILMN": "Health Care",
    "BIIB": "Health Care",
    "VRTX": "Health Care",
    "ALNY": "Health Care",
    "MRNA": "Health Care",
    "BNTX": "Health Care",
    "PFE": "Health Care",
    "JNJ": "Health Care",
    "CAH": "Health Care",
    "ABC": "Health Care",
    "NVO": "Health Care",
    "AZN": "Health Care",
    "GSK": "Health Care",
    "NOVN": "Health Care",
    "ROG": "Health Care",
    "SNY": "Health Care",
    "BAYRY": "Health Care",
    "RHHBY": "Health Care",
    "XLV": "Health Care",

    # --- Industrials ---
    "CAT": "Industrials",
    "GE": "Industrials",
    "HON": "Industrials",
    "UPS": "Industrials",
    "RTX": "Industrials",
    "LMT": "Industrials",
    "NOC": "Industrials",
    "GD": "Industrials",
    "BA": "Industrials",
    "HII": "Industrials",
    "L3H": "Industrials",
    "LHX": "Industrials",
    "TDG": "Industrials",
    "LDOS": "Industrials",
    "SAIC": "Industrials",
    "DE": "Industrials",
    "EMR": "Industrials",
    "ITW": "Industrials",
    "ETN": "Industrials",
    "SHW": "Industrials",
    "FDX": "Industrials",
    "WM": "Industrials",
    "RSG": "Industrials",
    "CSX": "Industrials",
    "NSC": "Industrials",
    "UNP": "Industrials",
    "CHRW": "Industrials",
    "EXPD": "Industrials",
    "XPO": "Industrials",
    "JBHT": "Industrials",
    "KNX": "Industrials",
    "CNI": "Industrials",
    "CP": "Industrials",
    "DAL": "Industrials",
    "UAL": "Industrials",
    "AAL": "Industrials",
    "LUV": "Industrials",
    "ALK": "Industrials",
    "XLI": "Industrials",
    "ITA": "Industrials",
    "XAR": "Industrials",

    # --- Materials ---
    "LIN": "Materials",
    "APD": "Materials",
    "ECL": "Materials",
    "PPG": "Materials",
    "NEM": "Materials",
    "GOLD": "Materials",
    "AEM": "Materials",
    "FNV": "Materials",
    "WPM": "Materials",
    "RGLD": "Materials",
    "FCX": "Materials",
    "NUE": "Materials",
    "STLD": "Materials",
    "DOW": "Materials",
    "VMC": "Materials",
    "MLM": "Materials",
    "XLB": "Materials",
    "GDX": "Materials",
    "GDXJ": "Materials",

    # --- Real Estate ---
    "PLD": "Real Estate",
    "SPG": "Real Estate",
    "O": "Real Estate",
    "AMT": "Real Estate",
    "CCI": "Real Estate",
    "SBAC": "Real Estate",
    "DLR": "Real Estate",
    "EQIX": "Real Estate",
    "PSA": "Real Estate",
    "EXR": "Real Estate",
    "AVB": "Real Estate",
    "EQR": "Real Estate",
    "MAA": "Real Estate",
    "CPT": "Real Estate",
    "UDR": "Real Estate",
    "ESS": "Real Estate",
    "INVH": "Real Estate",
    "AMH": "Real Estate",
    "SFR": "Real Estate",
    "VTR": "Real Estate",
    "WELL": "Real Estate",
    "PEAK": "Real Estate",
    "OHI": "Real Estate",
    "SBRA": "Real Estate",
    "NHI": "Real Estate",
    "HR": "Real Estate",
    "DOC": "Real Estate",
    "CTRE": "Real Estate",
    "MPW": "Real Estate",
    # NOTE: "LTC" collides with Litecoin (crypto). Sector map covers equities only.
    # Crypto symbols should use qualified form (e.g., "LTC-USD").
    "LTC": "Real Estate",
    "SNH": "Real Estate",
    "XLRE": "Real Estate",
    "VNQ": "Real Estate",

    # --- Utilities ---
    "SO": "Utilities",
    "DUK": "Utilities",
    "D": "Utilities",
    "NEE": "Utilities",
    "AES": "Utilities",
    "AEE": "Utilities",
    "AEP": "Utilities",
    "EXC": "Utilities",
    "PCG": "Utilities",
    "ED": "Utilities",
    "AWK": "Utilities",
    "ES": "Utilities",
    "ETR": "Utilities",
    "PPL": "Utilities",
    "XEL": "Utilities",
    "WEC": "Utilities",
    "CNP": "Utilities",
    "NI": "Utilities",
    "OGE": "Utilities",
    "PNW": "Utilities",
    "IDA": "Utilities",
    "NWE": "Utilities",
    "AVA": "Utilities",
    "POR": "Utilities",
    "HE": "Utilities",
    "SRE": "Utilities",
    "PEG": "Utilities",
    "XLU": "Utilities",

    # --- Shipping ---
    "MATX": "Industrials",
    "ZIM": "Industrials",
    "DAC": "Industrials",
    "GOGL": "Industrials",
    "SBLK": "Industrials",
    "EGLE": "Industrials",
    "BDRY": "Industrials",

    # --- Broad Market ETFs ---
    "SPY": "Broad Market",
    "QQQ": "Broad Market",
    "IWM": "Broad Market",
    "DIA": "Broad Market",

    # --- Fixed Income ---
    "TLT": "Fixed Income",
    "IEF": "Fixed Income",
    "SHY": "Fixed Income",
    "BND": "Fixed Income",
    "AGG": "Fixed Income",
    "TIPS": "Fixed Income",
    "TMF": "Fixed Income",
    "HYG": "Fixed Income",
    "LQD": "Fixed Income",

    # --- Commodities ---
    "GLD": "Commodities",
    "IAU": "Commodities",
    "SGOL": "Commodities",
    "SLV": "Commodities",
    "USO": "Commodities",

    # --- Currencies ---
    "UUP": "Currencies",

    # --- Crypto ---
    "IBIT": "Crypto",
    "ETHA": "Crypto",
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "SOL-USD": "Crypto",
    "AVAX-USD": "Crypto",
    "MATIC-USD": "Crypto",
    "LINK-USD": "Crypto",
    "UNI-USD": "Crypto",

    # --- Volatility ---
    "VIX": "Volatility",
    "VXX": "Volatility",
    "UVXY": "Volatility",
    "SVXY": "Volatility",

    # --- Emerging Markets ETFs ---
    "FXI": "Emerging Markets",
    "KWEB": "Emerging Markets",
    "EEM": "Emerging Markets",
    "VWO": "Emerging Markets",
    "MCHI": "Emerging Markets",

    # --- NSRGY (Consumer Staples, international) ---
    "NSRGY": "Consumer Staples",
}
